fix: include bun.lock in dockerfile for frontend
`bun.lock` was not being copied over to the container, so inside the container dependencies were being quietly updated. In this instance, typescript was quietly updated from `5.8.3` to `5.9` which introduces a [change](https://devblogs.microsoft.com/typescript/announcing-typescript-5-9/) that resulted in this error during build:

<details>
<summary>
Output
</summary>

```
 => ERROR [omni frontend 1/3] RUN --mount=type=cache,target=/src/node_modules,id=omni/src/node_modules bun run build ${JS_BUILD_ARGS}                                            1.3s
------
 > [omni frontend 1/3] RUN --mount=type=cache,target=/src/node_modules,id=omni/src/node_modules bun run build ${JS_BUILD_ARGS}:
0.069 $ vue-tsc && vite build
1.129 src/methods/index.ts(144,53): error TS2345: Argument of type 'Uint8Array<ArrayBufferLike>[]' is not assignable to parameter of type 'BlobPart[]'.
1.129   Type 'Uint8Array<ArrayBufferLike>' is not assignable to type 'BlobPart'.
1.129     Type 'Uint8Array<ArrayBufferLike>' is not assignable to type 'ArrayBufferView<ArrayBuffer>'.
1.129       Types of property 'buffer' are incompatible.
1.129         Type 'ArrayBufferLike' is not assignable to type 'ArrayBuffer'.
1.129           Type 'SharedArrayBuffer' is not assignable to type 'ArrayBuffer'.
1.129             Types of property '[Symbol.toStringTag]' are incompatible.
1.129               Type '"SharedArrayBuffer"' is not assignable to type '"ArrayBuffer"'.
1.138 error: script "build" exited with code 1
------
failed to solve: process "/bin/sh -c bun run build ${JS_BUILD_ARGS}" did not complete successfully: exit code: 1
make: *** [Makefile:398: docker-compose-up] Error 1
```
</details>

With this PR I copy over `bun.lock` and for good measure I added [`--frozen-lockfile`](https://bun.com/docs/cli/install#production-mode) which will throw an error if the `bun.lock` is out of date with `package.json` - to prevent this from happening by adding something to `package.json` without updating the lockfile.

Signed-off-by: Edward Sammut Alessi <edward.sammutalessi@siderolabs.com>